#!/bin/zsh
set -euo pipefail
setopt NULL_GLOB

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/homebrew/bin:$HOME/.local/bin:$HOME/.cargo/bin"

INSTALL_ROOT="${INSTALL_ROOT:-$HOME/InfobizAgents}"
HERMES_ROOT="${HERMES_ROOT:-$HOME/.hermes}"
HERMES_AGENT_ROOT="$HERMES_ROOT/hermes-agent"
COPYWRITER_ROOT="$HERMES_ROOT/profiles/copywriter"
DESIGNER_ROOT="$HERMES_ROOT/profiles/designer"
TECH_ROOT="$HERMES_ROOT/profiles/tech"
WEB_SHELL_ROOT="$INSTALL_ROOT/web-shell"
LOG_FILE="$INSTALL_ROOT/update.log"
VERSION="${VERSION:-0.1.0}"
BASE_URL="${BASE_URL:-https://github.com/temaserditov/infobiz-agents-installer/releases/download/v$VERSION}"
WEB_SHELL_URL="${WEB_SHELL_URL:-$BASE_URL/agent-web-shell-$VERSION.tar.gz}"
PROFILE_URL="${PROFILE_URL:-$BASE_URL/infobiz-agent-profile-marketer-$VERSION.tar.gz}"
HERMES_IMAGE_REFERENCE_PATCH_URL="${HERMES_IMAGE_REFERENCE_PATCH_URL:-https://raw.githubusercontent.com/temaserditov/infobiz-agents-installer/main/scripts/patch-hermes-image-reference.py}"
TECH_NO_CODE_PATCH_URL="${TECH_NO_CODE_PATCH_URL:-https://raw.githubusercontent.com/temaserditov/infobiz-agents-installer/main/scripts/patch-tech-no-code-defaults.py}"

say() {
  printf "==> %s\n" "$1"
}

fail() {
  printf "\nERROR: %s\n" "$1" >&2
  printf "Log file: %s\n" "$LOG_FILE" >&2
  exit 1
}

patch_markdown_file() {
  local file="$1"
  local title="$2"
  /bin/mkdir -p "$(/usr/bin/dirname "$file")"
  "$HERMES_AGENT_ROOT/venv/bin/python" - "$file" "$title" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
title = sys.argv[2]
text = path.read_text(encoding="utf-8", errors="ignore") if path.exists() else f"# {title}\n"

start = "<!-- INFOBIZ_GPT_IMAGE_2_HIGH_PATCH_START -->"
end = "<!-- INFOBIZ_GPT_IMAGE_2_HIGH_PATCH_END -->"
block = f"""{start}

## Infobiz image generation patch

This section is an installer patch. It has priority for image-generation requests.

- If the user asks to generate/create/make/draw an image, cover, banner, creative, illustration, or visual, generate the actual image.
- Do not answer with only a prompt unless the user explicitly asks for a prompt or image generation is technically unavailable.
- Use GPT-Image 2 High through the authorized Hermes/OpenAI-Codex image provider.
- Do not ask for an API key.
- Do not use OpenAI API, FAL API, Lao Zhang, or a third-party provider unless the user explicitly asks for that route.
- Do not create the requested image manually with Python, Pillow, HTML, CSS, canvas, SVG, screenshots, or any local drawing/compositing method.
- Do not generate a background and then overlay text/elements manually with code.
- If text, labels, badges, arrows, UI fragments, or other elements must appear in the image, include them in the GPT-Image 2 prompt itself.
- Local code may only help with file handling: downloading, saving, converting, or sending the generated image. It must not draw, compose, typeset, or decorate the requested image.
- In Telegram, send the generated result as a native image when possible: image URL or `MEDIA:/absolute/path`.

Reference-photo/person edit contract:

- If the user attaches a source photo/image of a person and asks to keep the face, preserve identity, extend the body, change clothes, change the background, make full-height, or edit only part of the image, treat the original person as a locked identity reference.
- If the user says this is their face or their agent must use their face in creatives, help with that exact task. Do not moralize, argue, refuse, or redirect to a generic model/person.
- For these tasks, always call `image_generate` with `reference_image` set to the local source image path/url. Do not use plain text-only generation.
- Preserve the exact same face, head shape, haircut, hairline, ears, neck, skin tone, expression, gaze, and visible identity features from the source image.
- Do not replace the head or face with another person.
- Do not generate a similar-looking model from a text description.
- Do not crop away the original face to hide a mismatch.
- Use GPT-Image 2 High in image edit / image-to-image / inpaint / outpaint / reference-preserving mode when available.
- The internal prompt must say: "Preserve the original face, head, hair, neck, expression, and identity exactly from the provided source image. Do not replace the person. Edit/extend only the requested non-identity areas."
- Do not write "I generated it with face preservation in the prompt"; that means you used the wrong route. Correct wording: "Generated by editing the source image with reference_image."
- If the generated result changes the face/head, treat it as a failed draft. Regenerate with stronger identity-lock instructions and the original image as reference/input. Do not send a changed-identity result as final.
- Only ask the user for a better source image or mask if repeated attempts are likely to keep changing the identity.

Correct behavior: generate via `image_generate`, send the image, then add a short caption and 1-3 iteration options.

Fallback only if generation is unavailable: clearly say the image tool is not available and provide a temporary GPT-Image 2 prompt.

{end}"""

pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
if pattern.search(text):
    text = pattern.sub(block, text)
else:
    text = text.rstrip() + "\n\n" + block + "\n"
path.write_text(text, encoding="utf-8")
PY
}

configure_designer_image_generation() {
  local config_path="$DESIGNER_ROOT/config.yaml"
  "$HERMES_AGENT_ROOT/venv/bin/python" - "$config_path" <<'PY'
from pathlib import Path
import sys

try:
    import yaml
except Exception as exc:
    raise SystemExit(f"PyYAML is required to configure designer image generation: {exc}")

path = Path(sys.argv[1])
data = yaml.safe_load(path.read_text() if path.exists() else "") or {}
if not isinstance(data, dict):
    data = {}

platform_toolsets = data.setdefault("platform_toolsets", {})
if not isinstance(platform_toolsets, dict):
    platform_toolsets = {}
    data["platform_toolsets"] = platform_toolsets

for platform in ("cli", "telegram", "web"):
    current = platform_toolsets.get(platform)
    if not isinstance(current, list):
        current = []
    if "image_gen" not in current:
        current.append("image_gen")
    platform_toolsets[platform] = current

image_gen = data.setdefault("image_gen", {})
if not isinstance(image_gen, dict):
    image_gen = {}
    data["image_gen"] = image_gen
image_gen["provider"] = "openai-codex"
image_gen["model"] = "gpt-image-2-high"
openai_codex = image_gen.setdefault("openai-codex", {})
if not isinstance(openai_codex, dict):
    openai_codex = {}
    image_gen["openai-codex"] = openai_codex
openai_codex["model"] = "gpt-image-2-high"

path.write_text(yaml.safe_dump(data, allow_unicode=True, sort_keys=False))
PY
}

patch_hermes_image_reference_support() {
  local patcher="${TMPDIR:-/tmp}/patch-hermes-image-reference.py"
  /usr/bin/curl -fsSL "$HERMES_IMAGE_REFERENCE_PATCH_URL" -o "$patcher"
  "$HERMES_AGENT_ROOT/venv/bin/python" "$patcher" "$HERMES_AGENT_ROOT"
}

patch_tech_no_code_defaults() {
  local patcher="${TMPDIR:-/tmp}/patch-tech-no-code-defaults.py"
  /usr/bin/curl -fsSL "$TECH_NO_CODE_PATCH_URL" -o "$patcher"
  "$HERMES_AGENT_ROOT/venv/bin/python" "$patcher" "$TECH_ROOT"
}

update_web_shell() {
  local workdir payload
  workdir="$(/usr/bin/mktemp -d "${TMPDIR:-/tmp}/infobiz-web-shell.XXXXXX")"
  payload="$workdir/agent-web-shell.tar.gz"
  /usr/bin/curl -fsSL "$WEB_SHELL_URL" -o "$payload"
  /usr/bin/tar -xzf "$payload" -C "$workdir"
  [[ -d "$workdir/web-shell" ]] || return 1
  /bin/mkdir -p "$WEB_SHELL_ROOT"
  /usr/bin/ditto "$workdir/web-shell/public" "$WEB_SHELL_ROOT/public"
  /usr/bin/ditto "$workdir/web-shell/scripts" "$WEB_SHELL_ROOT/scripts"
  for file in server.mjs runner.py package.json README.md; do
    [[ -f "$workdir/web-shell/$file" ]] && /bin/cp "$workdir/web-shell/$file" "$WEB_SHELL_ROOT/$file"
  done
  /usr/bin/xattr -dr com.apple.quarantine "$WEB_SHELL_ROOT" >/dev/null 2>&1 || true
}

update_copywriter_profile() {
  local workdir payload source_dir backup_dir item
  workdir="$(/usr/bin/mktemp -d "${TMPDIR:-/tmp}/infobiz-profile.XXXXXX")"
  payload="$workdir/profile.tar.gz"
  backup_dir="$HERMES_ROOT/.archives/copywriter-update.$(/bin/date +%Y%m%d%H%M%S)"
  /usr/bin/curl -fsSL "$PROFILE_URL" -o "$payload"
  /usr/bin/tar -xzf "$payload" -C "$workdir"
  source_dir="$workdir/profile/agents/copywriter"
  [[ -d "$source_dir" ]] || return 1

  /bin/mkdir -p "$COPYWRITER_ROOT" "$backup_dir"
  for item in SOUL.md IDENTITY.md AGENTS.md OUTPUT_STANDARDS.md TEST_SCENARIOS.md COMMANDS.md FIRST_RUN.md READY_CHECKLIST.md README.md COPY_BRIEF.md MARKETER_HANDOFF.md DESIGNER_TECH_HANDOFF.md knowledge skills; do
    [[ -e "$COPYWRITER_ROOT/$item" ]] && /usr/bin/ditto "$COPYWRITER_ROOT/$item" "$backup_dir/$item" || true
  done

  /usr/bin/rsync -a --delete \
    --exclude '.env' \
    --exclude 'auth.json' \
    --exclude 'config.yaml' \
    --exclude 'sessions/' \
    --exclude 'logs/' \
    --exclude 'memories/' \
    --exclude 'cache/' \
    --exclude 'cron/' \
    --exclude 'test-runs/' \
    "$source_dir/" "$COPYWRITER_ROOT/"
  /usr/bin/xattr -dr com.apple.quarantine "$COPYWRITER_ROOT" >/dev/null 2>&1 || true
}

restart_launch_agent() {
  local label="$1"
  local plist="$2"
  local uid
  uid="$(/usr/bin/id -u)"
  if [[ -f "$plist" ]]; then
    /bin/launchctl bootout "gui/$uid" "$plist" >/dev/null 2>&1 || true
    /bin/launchctl bootstrap "gui/$uid" "$plist" >/dev/null 2>&1 || /bin/launchctl load "$plist" >/dev/null 2>&1 || true
  fi
  /bin/launchctl kickstart -k "gui/$uid/$label" >/dev/null 2>&1 || true
}

[[ "$(/usr/bin/uname -s)" == "Darwin" ]] || fail "This updater supports macOS only."
[[ -d "$HERMES_AGENT_ROOT" ]] || fail "Hermes is not installed. Run the full installer first."
[[ -x "$HERMES_AGENT_ROOT/venv/bin/python" ]] || fail "Hermes Python venv is missing. Run the full installer first."
[[ -d "$COPYWRITER_ROOT" ]] || fail "Copywriter profile is not installed. Run the full installer first."
[[ -d "$DESIGNER_ROOT" ]] || fail "Designer profile is not installed. Run the full installer first."
[[ -d "$TECH_ROOT" ]] || fail "Tech profile is not installed. Run the full installer first."

/bin/mkdir -p "$INSTALL_ROOT"
: > "$LOG_FILE"
printf "Infobiz Agents patch-only update log\nStarted: %s\n" "$(/bin/date)" >> "$LOG_FILE"

say "Patching designer image generation rules"
patch_markdown_file "$DESIGNER_ROOT/SOUL.md" "SOUL.md" >> "$LOG_FILE" 2>&1
patch_markdown_file "$DESIGNER_ROOT/IMAGE_GENERATION_POLICY.md" "IMAGE_GENERATION_POLICY.md" >> "$LOG_FILE" 2>&1
patch_markdown_file "$DESIGNER_ROOT/skills/gpt-image-2-generation-basic/SKILL.md" "gpt-image-2-generation-basic" >> "$LOG_FILE" 2>&1

say "Patching Hermes image reference support"
patch_hermes_image_reference_support >> "$LOG_FILE" 2>&1 || fail "Could not patch Hermes image reference support"

say "Patching tech no-code defaults"
patch_tech_no_code_defaults >> "$LOG_FILE" 2>&1 || fail "Could not patch tech no-code defaults"

say "Updating copywriter profile"
update_copywriter_profile >> "$LOG_FILE" 2>&1 || fail "Could not update copywriter profile"

say "Updating WebShell"
update_web_shell >> "$LOG_FILE" 2>&1 || fail "Could not update WebShell"

say "Configuring GPT-Image 2 High"
configure_designer_image_generation >> "$LOG_FILE" 2>&1 || fail "Could not configure GPT-Image 2 High for designer"

say "Restarting designer gateway"
LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
restart_launch_agent "ai.hermes.gateway-copywriter" "$LAUNCH_AGENTS/ai.hermes.gateway-copywriter.plist"
restart_launch_agent "ai.hermes.gateway-designer" "$LAUNCH_AGENTS/ai.hermes.gateway-designer.plist"
restart_launch_agent "ai.hermes.gateway-tech" "$LAUNCH_AGENTS/ai.hermes.gateway-tech.plist"
restart_launch_agent "com.infobiz.agents.web-shell" "$LAUNCH_AGENTS/com.infobiz.agents.web-shell.plist"

say "Patch complete"
if [[ -f "$INSTALL_ROOT/web-shell.url" ]]; then
  printf "WebShell: %s\n" "$(/usr/bin/head -n 1 "$INSTALL_ROOT/web-shell.url")"
fi
